### ISSUE TITLE
polypy provision list templates broken.

### ISSUE THREAD

**Issue by mjmunger** [mjmunger/PolyPyTools#1]
```
polypy provision list templates
Traceback (most recent call last):
  File "/usr/local/bin/polypy", line 65, in <module>
    from poly_py_tools import provision
  File "/home/michael/py/PolyPyTools/poly_py_tools/provision.py", line 46, in <module>
    parser = SipConfParser(os.path.join(paths['asterisk'], 'sip.conf'))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by mjmunger** [comment]
Pull request issued.

**Comment by mjmunger** [comment]
Fixed.
