### ISSUE TITLE
polypy sip broken

### ISSUE THREAD

**Issue by mjmunger** [mjmunger/PolyPyTools#16]
```
root@pbx:/usr/src/PolyPyTools# polypy sip
Traceback (most recent call last):
  File "/usr/local/bin/polypy", line 84, in <module>
    from poly_py_tools import sip_manager
  File "/usr/local/lib/python3.7/site-packages/poly_py_tools/sip_manager.py", line 45, in <module>
    from poly_py_tools.sip_parser import SipConfParser
  File "/usr/local/lib/python3.7/site-packages/poly_py_tools/sip_parser.py", line 2, in <module>
    from poly_py_tools.template import Template
  File "/usr/local/lib/python3.7/site-packages/poly_py_tools/template.py", line 2, in <module>
    from poly_py_tools.registration import Registration
  File "/usr/local/lib/python3.7/site-packages/poly_py_tools/registration.py", line 1, in <module>
    from poly_py_tools.pjsip.aor import Aor
ModuleNotFoundError: No module named 'poly_py_tools.pjsip'
```

**Comment by mjmunger** [comment]
Closed with PR #22
