### ISSUE TITLE
polypy provision

### ISSUE THREAD

**Issue by mjmunger** [mjmunger/PolyPyTools#17]
```
root@pbx:/usr/src/PolyPyTools# polypy provision
Traceback (most recent call last):
  File "/usr/local/bin/polypy", line 80, in <module>
    from poly_py_tools.provision import provision
  File "/usr/local/lib/python3.7/site-packages/poly_py_tools/provision.py", line 21, in <module>
    from poly_py_tools.provision_factory import ProvisionFactory
  File "/usr/local/lib/python3.7/site-packages/poly_py_tools/provision_factory.py", line 1, in <module>
    from poly_py_tools.provision.provision_polycom import ProvisionPolycom
ModuleNotFoundError: No module named 'poly_py_tools.provision.provision_polycom'; 'poly_py_tools.provision' is not a package
```

**Comment by mjmunger** [comment]
Closed with PR #22
