### ISSUE TITLE
polypy generate is not passing args like it should

### ISSUE THREAD

**Issue by mjmunger** [mjmunger/PolyPyTools#28]
```
root@example:~/clients/org.example# polypy pjsip generate 111 from DialPlanBuilder-L3_pbx_v1.csv 
Traceback (most recent call last):
  File "/usr/local/bin/polypy", line 54, in <module>
    polypy.run()
  File "/usr/src/PolyPyTools/poly_py_tools/polypy.py", line 15, in run
    from poly_py_tools.pjsip import pjsip
  File "/usr/src/PolyPyTools/poly_py_tools/pjsip/pjsip.py", line 36, in <module>
    runner = factory.get_runner(args)
  File "/usr/src/PolyPyTools/poly_py_tools/pjsip/pjsip_factory.py", line 8, in get_runner
    if args['<args>']:
KeyError: '<args>'
```

**Comment by mjmunger** [comment]
This was fixed, and has been merged into #27 's branch.
