### ISSUE TITLE
polypy init site does not create directory and firmware on brand new site

### ISSUE THREAD

**Issue by mjmunger** [mjmunger/PolyPyTools#37]
When using `polypy site init <site> <model>`, it should be able to create a site and populate the firmware. Right now, it just crashses.

```
root@pbx:~/clients/org.example# polypy site init org.example SPIP670
Traceback (most recent call last):
  File "/usr/local/bin/polypy", line 35, in <module>
    polypy.run()
  File "/usr/src/PolyPyTools/poly_py_tools/polypy.py", line 45, in run
    site.run()
  File "/usr/src/PolyPyTools/poly_py_tools/site/site.py", line 61, in run
    runner.run()
  File "/usr/src/PolyPyTools/poly_py_tools/site/site_configurator.py", line 17, in run
    self.init()
  File "/usr/src/PolyPyTools/poly_py_tools/site/site_configurator.py", line 30, in init
    for file in os.listdir(source_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/html/io.hph.pbx/p/org.example/firmware/4.0.15.1009/Config'
```

**Comment by mjmunger** [comment]
The temporary workaround (and possibly solution once added to code) is:
```
cd /var/www/html/io.foo.pbx/org.example/
ln -s ../firmware/
```

**Comment by mjmunger** [comment]
perhaps add `--firmware-symlink=/path/to/firmware/` as an option...
